--liquibase formatted sql
--changeset antoxakon:2  -- Формат: author:id
--comment: create table client_visit

create table if not exists client_visit
(
    id   bigint generated by default as identity primary key,
    visit_id       uuid         not null,
    owner_id       uuid         not null,
    doctor_id      uuid         not null,
    animal_id      uuid         not null,
    reason_request varchar(255) not null,
    visit_date     timestamp(6) not null
);