--liquibase formatted sql
--changeset antoxakon:3  -- Формат: author:id
--comment: create table full_info_visit

create table if not exists full_info_visit
(
    id             bigint generated by default as identity primary key,
    visit_id       uuid         not null,
    owner          varchar(255),
    doctor         varchar(255),
    animal         varchar(255),
    reason_request varchar(255) not null,
    visit_date     timestamp(6) not null
);